### ISSUE TITLE
Adapter red

### ISSUE THREAD

**Issue by TeRa2020** [TA2k/ioBroker.lg-thinq#2]
Hello, 

 First of all a big thank you for providing this adapter.

Since a few days the adapter turns to red, red, green.  Before this I was able to use it without  any problems.

Here is my log...

2021-10-03 00:14:02.327 - info: lg-thinq.0 (9842) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.lg-thinq, node: v14.17.2, js-controller: 3.3.18
--
2021-10-03 00:14:05.065 - info: lg-thinq.0 (9842) Login successful
2021-10-03 00:14:05.637 - error: lg-thinq.0 (9842) Error: Request failed with status code 400
2021-10-03 00:14:05.643 - error: lg-thinq.0 (9842) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-10-03 00:14:05.645 - error: lg-thinq.0 (9842) unhandled promise rejection: Cannot read property 'length' of undefined
2021-10-03 00:14:05.649 - error: lg-thinq.0 (9842) TypeError: Cannot read property 'length' of undefined
at LgThinq.getListDevices (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:470:40)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async LgThinq.onReady (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:94:37)
2021-10-03 00:14:05.652 - error: lg-thinq.0 (9842) Cannot read property 'length' of undefined
2021-10-03 00:14:05.840 - info: lg-thinq.0 (9842) terminating
2021-10-03 00:14:05.841 - warn: lg-thinq.0 (9842) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-10-03 00:14:06.425 - error: host.raspberrypi instance system.adapter.lg-thinq.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-10-03 00:14:06.426 - info: host.raspberrypi Restart adapter system.adapter.lg-thinq.0 because enabled

Can anyone help

Best regards

**Comment by TA2k** [comment]
I add additional logging please reinstall. But it looks like you have no homes in your account

**Comment by TeRa2020** [comment]
Hi TA2k
I got it running again. It crashed due to missing new agreements to LGs new terms of use. After clicking these in the app the adapter seems to work properly again.

Thank you so much for this nice adapter and your fast response 

Best regards
