### ISSUE TITLE
Absturz bei Version 0.30

### ISSUE THREAD

**Issue by Bulls91** [TA2k/ioBroker.lg-thinq#34]
Wenn ich den Adapter Starte stürzt dieser nach kurzer Zeit mit der folgenden Fehlermeldung ab:

2023-12-18 22:39:30.762 - info: lg-thinq.0 (2261846) Login successful
--
2023-12-18 22:39:33.632 - info: lg-thinq.0 (2261846) Found: 1 devices
2023-12-18 22:39:33.633 - info: lg-thinq.0 (2261846) Create or update datapoints for af776140-58c8-11e9-b0c4-7440be268613
2023-12-18 22:39:41.722 - info: lg-thinq.0 (2261846) Update raw datapoints for af776140-58c8-11e9-b0c4-7440be268613
2023-12-18 22:40:22.708 - error: lg-thinq.0 (2261846) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-18 22:40:22.708 - error: lg-thinq.0 (2261846) unhandled promise rejection: result is not iterable
2023-12-18 22:40:22.710 - error: lg-thinq.0 (2261846) TypeError: result is not iterable
at /opt/iobroker/node_modules/iobroker.lg-thinq/main.js:357:34
at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-18 22:40:22.710 - error: lg-thinq.0 (2261846) result is not iterable
2023-12-18 22:40:22.716 - info: lg-thinq.0 (2261846) terminating
2023-12-18 22:40:22.717 - warn: lg-thinq.0 (2261846) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-18 22:40:23.217 - info: lg-thinq.0 (2261846) terminating
2023-12-18 22:40:23.246 - error: host.ioBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-18 22:40:23.246 - error: host.ioBroker Caught by controller[0]: TypeError: result is not iterable
2023-12-18 22:40:23.246 - error: host.ioBroker Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.lg-thinq/main.js:357:34
2023-12-18 22:40:23.246 - error: host.ioBroker Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-18 22:40:23.246 - error: host.ioBroker instance system.adapter.lg-thinq.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-12-18 22:40:23.246 - info: host.ioBroker Restart adapter system.adapter.lg-thinq.0 because enabled

Nach dem der Fehler kam startet der Adapter automatisch neu und generiert nach ein paar Sekunden wieder den gleichen Fehler. Bei Version 0.20 trat diese Problematik nicht auf. Kann jemand weiterhelfen?

**Comment by Lucky-ESA** [comment]
Lade mal bitte vom GIT.

**Comment by Bulls91** [comment]
Habe es nochmal von Git geladen und erhalten dann nach dem starten folgende Fehler: 


12-19 08:46:27.747 - info: lg-thinq.0 (2313564) Login successful
--
2023-12-19 08:46:39.317 - info: lg-thinq.0 (2313564) Found: 1 devices
2023-12-19 08:46:39.317 - info: lg-thinq.0 (2313564) Create or update datapoints for af776140-58c8-11e9-b0c4-7440be268613
2023-12-19 08:46:40.164 - warn: lg-thinq.0 (2313564) Object of state "lg-thinq.0.af776140-58c8-11e9-b0c4-7440be268613.sdsGuide" is missing the required property "common.type"
2023-12-19 08:46:42.428 - error: lg-thinq.0 (2313564) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-19 08:46:42.428 - error: lg-thinq.0 (2313564) unhandled promise rejection: Cannot set properties of undefined (setting 'thinq2')
2023-12-19 08:46:42.430 - error: lg-thinq.0 (2313564) TypeError: Cannot set properties of undefined (setting 'thinq2')
at LgThinq.onReady (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:240:65)
2023-12-19 08:46:42.430 - error: lg-thinq.0 (2313564) Cannot set properties of undefined (setting 'thinq2')
2023-12-19 08:46:42.436 - info: lg-thinq.0 (2313564) terminating
2023-12-19 08:46:42.436 - warn: lg-thinq.0 (2313564) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-19 08:46:42.937 - info: lg-thinq.0 (2313564) terminating
2023-12-19 08:46:42.969 - error: host.ioBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-19 08:46:42.969 - error: host.ioBroker Caught by controller[1]: TypeError: Cannot set properties of undefined (setting 'thinq2')
2023-12-19 08:46:42.969 - error: host.ioBroker Caught by controller[1]: at LgThinq.onReady (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:240:65)
2023-12-19 08:46:42.969 - error: host.ioBroker instance system.adapter.lg-thinq.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-12-19 08:46:42.969 - info: host.ioBroker Restart adapter system.adapter.lg-thinq.0 because enabled
2023-12-19 08:47:13.133 - info: host.ioBroker instance system.adapter.lg-thinq.0 started with pid 2313665
2023-12-19 08:47:13.595 - info: lg-thinq.0 (2313665) starting. Version 0.3.0 (non-npm: TA2k/ioBroker.lg-thinq#8b0ed93dacb6c1412d1846c963204c5fcd13da06) in /opt/iobroker/node_modules/iobroker.lg-thinq, node: v18.19.0, js-controller: 5.0.17

**Comment by Lucky-ESA** [comment]
Was steht in diesen 2 Datenpunkte.
lg-thinq.0.xxx.deviceType
lg-thinq.0.xxx.platformType
Das ist schon echt merkwürdig bei dir.

**Comment by Bulls91** [comment]
Folgendes steht bei den beiden Punkten:

lg-thinq.0.xxx.deviceType = 101
lg-thinq.0.xxx.platformType = thinq1

**Comment by Lucky-ESA** [comment]
Leider benötige ich ein Log. Kannst du bitte die aktuelle GIT Version laden. Dann in der Instanz Einstellung das Loglevel vom Adapter auf Debug stellen und dann bis zum Crash laufen lassen. Das komplette Logfile bitte an meiner Email senden.
github@luckyskills.de

Sorry für die Umstände.

Gruß//Lucky

**Comment by Bulls91** [comment]
habe vorgestern die letzte Version von GIT geladen und der Fehler ist nicht mehr aufgetreten, weshalb ich Dir auch keinen Log zugeschickt habe. Vielen Dank für die Arbeit, das Fixen und die Hilfe :)

**Comment by Lucky-ESA** [comment]
Die letzte GIT Version war auch fehlerhaft. Bitte auf die 0.3.1 aktualisieren. Die Fehlermeldung aus deinem 2 Beitrag ist noch nicht gefixt. Werde ich dann mit der 0.3.2 versuchen zu redizieren. Fixen ist nicht möglich da es sich hierbei um ein Timeout handelt. Wenn der LG Server kurzeitig ausfällt und du den Adapter in der Zeit neu startes, wird dieser Fehler wieder kommen.

**Comment by Lucky-ESA** [comment]
Next crash

```
2023-12-29 01:03:07.611 - error:  lg-thinq.0 (697092) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2023-12-29 01:03:07.612 - error: lg-thinq.0 (697092) unhandled promise rejection: device_array is not iterable
2023-12-29 01:03:07.614 - error: lg-thinq.0 (697092) TypeError: device_array is not iterable
at /opt/iobroker/node_modules/iobroker.lg-thinq/main.js:374:34
at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Bitte mal vom GIT laden und testen.

**Comment by Bulls91** [comment]
habe nochmals von git geladen. Nun erhalte ich im Protokoll immer folgende Einträge:

	WRONG WORKLIST RESULT: {"returnCd":"0000","returnMsg":"OK","workList":{"deviceId":"af776140-58c8-11e9-b0c4-7440be268613","deviceState":"E","format":"B64","returnCode":"0000","returnData":"AgQFAf8CAAABAAEA","stateCode":"S","workId":"n-af776140-58c8-11e9-b0c4-7440be268613"}}

lg-thinq.0
2024-01-06 21:46:58.590	info	WRONG WORKLIST: []

lg-thinq.0
2024-01-06 21:46:28.586	info	WRONG WORKLIST RESULT: {"returnCd":"0000","returnMsg":"OK","workList":{"deviceId":"af776140-58c8-11e9-b0c4-7440be268613","deviceState":"E","format":"B64","returnCode":"0000","returnData":"AgQFAf8CAAABAAEA","stateCode":"S","workId":"n-af776140-58c8-11e9-b0c4-7440be268613"}}

lg-thinq.0
2024-01-06 21:46:28.586	info	WRONG WORKLIST: []

lg-thinq.0
2024-01-06 21:45:58.643	info	WRONG WORKLIST RESULT: {"returnCd":"0000","returnMsg":"OK","workList":{"deviceId":"af776140-58c8-11e9-b0c4-7440be268613","deviceState":"E","format":"B64","returnCode":"0000","returnData":"AgQFAf8CAAABAAEA","stateCode":"S","workId":"n-af776140-58c8-11e9-b0c4-7440be268613"}}

lg-thinq.0
2024-01-06 21:45:58.642	info	WRONG WORKLIST: []

lg-thinq.0
2024-01-06 21:45:28.578	info	WRONG WORKLIST RESULT: {"returnCd":"0000","returnMsg":"OK","workList":{"deviceId":"af776140-58c8-11e9-b0c4-7440be268613","deviceState":"E","format":"B64","returnCode":"0000","returnData":"AgQFAf8CAAABAAEA","stateCode":"S","workId":"n-af776140-58c8-11e9-b0c4-7440be268613"}}

lg-thinq.0
2024-01-06 21:45:28.578	info	WRONG WORKLIST: []

lg-thinq.0
2024-01-06 21:44:58.610	info	WRONG WORKLIST RESULT: {"returnCd":"0000","returnMsg":"OK","workList":{"deviceId":"af776140-58c8-11e9-b0c4-7440be268613","deviceState":"E","format":"B64","returnCode":"0000","returnData":"AgQFAf8CAAABAAEA","stateCode":"S","workId":"n-af776140-58c8-11e9-b0c4-7440be268613"}}

lg-thinq.0
2024-01-06 21:44:58.610	info	WRONG WORKLIST: []

**Comment by Lucky-ESA** [comment]
Danke für die Info Kannst du bitte erneut vom GIT laden.

**Comment by Lucky-ESA** [comment]
Es gabt leider noch einige andere Fehler. Kannst du mla bitte neu vom GIT laden.

**Comment by Bulls91** [comment]
Ist erledigt, habe die Version installiert

**Comment by Bulls91** [comment]
der Fehler trat nun nicht mehr auf. Vielen Dank fürs fixen:)
